config/routes.rb
MikeOdmark::Application.routes.draw do
  devise_for :admins

  root to: "home#index"

  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy], path: "blog"
  resources :messages, only: [:new, :create], path: "contact"

  resource :work, only: [:show, :edit, :update], controller: "work"
  resource :info, only: [:show, :edit, :update], controller: "info"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/info.rb
class Info < ActiveRecord::Base
  set_table_name :info

  validates :content, presence: true
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  validates :title, :content, :email, presence: true

  attr_accessor :title, :content, :email

  def initialize(params={})
    @email = params[:email]
    @content = params[:content]
    @title = params[:title]
  end

  def persisted?
    false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include FriendlyId
  friendly_id :title, :use => :slugged

  default_scope order('created_at DESC')
end

app/models/work.rb
class Work < ActiveRecord::Base
  set_table_name :work

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  before_filter do
    @current_page = "Info"
  end

  def show
    @content = Info.first_or_create.content
  end

  def edit
    @info = Info.first_or_create
  end

  def update
    @info = Info.first_or_create
    if @info.update_attributes(params[:info])
      redirect_to info_path
    else
      render :edit
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter do
    @current_page = "Contact"
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      ApplicationMailer.contact(@message)
      flash[:success] = "Message sent successfully."
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin!, except: [:index, :show]
  before_filter do
    @current_page = "Blog"
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    Post.find(params[:id]).delete
    redirect_to posts_path
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  before_filter do
    @current_page = "Work"
  end

  def show
    @content = Work.first_or_create.content
  end

  def edit
    @work = Work.first_or_create
  end

  def update
    @work = Work.first_or_create
    if @work.update_attributes(params[:work])
      redirect_to work_path
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  def nav_link title, path, current_page
    is_current = (current_page == title)
    content_tag(:li, class: is_current ? "current" : "") do
      link_to title, path
    end
  end

  def photo file_name, options = {}
    classes = "photo " + (options[:class] || "")
    content_tag(:span, class: classes) do
      image_tag "pages/#{file_name}.jpg", title: "All rights reserved ©#{Date.today.year}."
    end
  end
end

app/views/home/index.html.haml
#home
  = photo "home"

app/views/info/edit.html.haml
= simple_form_for @info, url: info_path(@info), method: "PUT" do |f|
  = f.input :content, as: :text, input_html: { class: "html-editor" }
  = f.submit class: "btn btn-primary"
  = link_to "Cancel", info_path, class: "btn"

app/views/info/show.html.haml
- if admin_signed_in?
  %p= link_to "Edit Info", edit_info_path, class: "btn btn-primary"
.html-output.clearfix
  = photo "info", class: "right"
  = raw(@content)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mike Odmark
    %meta{ name: "viewport", content: "user-scalable=no, initial-scale=1.0, maximum-scale=1.0, width=device-width" }
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "//use.typekit.net/jaq1ezd.js"
    :javascript
      try{Typekit.load();}catch(e){}
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  #wrapper
    .container
      %header
        %nav
          %ul
            = nav_link "Blog", posts_path, @current_page
            = nav_link "Info", info_path, @current_page
            %li.logo
              = link_to root_path do
                = image_tag "logo.png"
            = nav_link "Work", work_path, @current_page
            = nav_link "Contact", new_message_path, @current_page
        .wave
          = image_tag "div.png"

      %section#content
        - [:success, :alert, :error].each do |level|
          - unless flash[level].blank?
            .alert{ class: level }
              %a.close{ href: "#", data: { dismiss: "alert" } }
                = image_tag "icons/x.png"
              = flash[level]

        = yield

      #footer-push

  %footer
    .container
      #fine-print
        = "All rights reserved ©#{Date.today.year}."
        Website by
        = link_to "Some Weather Web Design & Programming", "http://www.someweather.com"
        |
        - if admin_signed_in?
          = link_to "Sign out", destroy_admin_session_path, method: :delete
        - else
          = link_to "Sign in", new_admin_session_path

app/views/messages/new.html.haml
#contact
  .row
    .span4
      = simple_form_for @message do |f|
        = f.input :email
        = f.input :title, label: "Subject"
        = f.input :content, as: :text, input_html: { rows: 10 }, label: "Message"

        = f.submit "Send Message", class: "btn btn-primary"
    .span7.offset1
      = photo "contact"

app/views/posts/_form.html.haml
= f.input :title
= f.input :content, as: :text, input_html: { class: "html-editor" }
= f.submit "Save", class: "btn btn-primary"
= link_to "Cancel", posts_path, class: "btn"

app/views/posts/_post.html.haml
.post
  .post-header
    - if single
      %h1= post.title
    - else
      %h2= link_to post.title, post
    - if admin_signed_in?
      = link_to image_tag("icons/pencil.png"), edit_post_path(post)
      = link_to image_tag("icons/x.png"), post_path(post), method: "delete", confirm: "Are you sure you want to remove this the post \"#{post.title}\"?"
    %p.post-date= post.updated_at.strftime("%B %e, %Y")
  %p.post-content.html-output= raw post.content

app/views/posts/edit.html.haml
= simple_form_for @post do |f|
  = render "form", { f: f }

app/views/posts/index.html.haml
- @posts.each do |post|
  = render partial: "post", locals: { post: post, single: false }
- if admin_signed_in?
  = link_to "Create New Blog Post", new_post_path, class: "btn btn-primary"

app/views/posts/new.html.haml
= simple_form_for @post do |f|
  = render "form", { f: f }

app/views/posts/show.html.haml
= render partial: "post", locals: { post: @post, single: true }

app/views/work/edit.html.haml
= simple_form_for @work, url: work_path(@work), method: "PUT" do |f|
  = f.input :content, as: :text, input_html: { class: "html-editor" }
  = f.submit class: "btn btn-primary"
  = link_to "Cancel", work_path, class: "btn"

app/views/work/show.html.haml
#work.row
  .span5
    = photo "work"
  .span6.offset1
    - if admin_signed_in?
      %p= link_to "Edit Work", edit_work_path, class: "btn btn-primary"
    .html-output= raw(@content)